=== maksunovs/Gems/src/main/resources/gemsXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/gems"
        xmlns:tns="http://www.example.com/gems"
        elementFormDefault="qualified">
    <element name="gem" type="tns:Gem" abstract="true"/>
    <element name="precious" type="tns:PreciousStone" substitutionGroup="tns:gem"/>
    <element name="semiprecious" type="tns:SemipreciousStone" substitutionGroup="tns:gem"/>
    <element name="gems">
        <complexType>
            <sequence>
                <element name="precious"
                         type="tns:PreciousStone"
                         minOccurs="0"
                         maxOccurs="unbounded"/>

                <element name="semiprecious"
                         type="tns:SemipreciousStone"
                         minOccurs="0"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    <complexType name="Gem">
        <sequence minOccurs="0" maxOccurs="unbounded">
            <element name="preciousness">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="precious"/>
                        <enumeration value="semiprecious"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="origin" type="string"/>
            <element name="visual-parameters" type="tns:VisualParameters"/>
            <element name="value" type="double"/>
            <element name="hardness">
                <simpleType>
                    <restriction base="double">
                        <minInclusive value="1"/>
                        <maxInclusive value="10"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
        <attribute name="name" type="string"/>
    </complexType>
    <complexType name="PreciousStone">
        <complexContent>
            <extension base="tns:Gem"/>
        </complexContent>
    </complexType>
    <complexType name="SemipreciousStone">
        <complexContent>
            <extension base="tns:Gem"/>
        </complexContent>
    </complexType>
    <complexType name="VisualParameters">
        <sequence minOccurs="0">
            <element name="color" type="string"/>
            <element name="transparency">
                <simpleType>
                    <restriction base="int">
                        <minInclusive value="0"/>
                        <maxInclusive value="100"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="lustre">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="adamantine"/>
                        <enumeration value="metallic"/>
                        <enumeration value="vitreous"/>
                        <enumeration value="waxy"/>
                        <enumeration value="silky"/>
                    </restriction>
                </simpleType>
            </element>
        </sequence>
    </complexType>
</schema>

=== maksunovs/Gems/src/test/java/gems.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/gems"
      xsi:schemaLocation="http://www.example.com/gems gemsXSD.xsd">
    <precious name="ruby">
        <preciousness>precious</preciousness>
        <origin>Australia</origin>
        <visual-parameters>
            <color>red</color>
            <transparency>85</transparency>
            <lustre>vitreous</lustre>
        </visual-parameters>
        <value>8.62</value>
        <hardness>9</hardness>
        <rarity>rare</rarity>
    </precious>
    <precious name="tourmaline">
        <preciousness>precious</preciousness>
        <origin>China</origin>
        <visual-parameters>
            <color>pink</color>
            <transparency>50</transparency>
            <lustre>vitreous</lustre>
        </visual-parameters>
        <value>10</value>
        <hardness>7</hardness>
        <rarity>rare</rarity>
    </precious>
    <precious name="diamond">
        <preciousness>precious</preciousness>
        <origin>Africa</origin>
        <visual-parameters>
            <color>colorless</color>
            <transparency>100</transparency>
            <lustre>adamantine</lustre>
        </visual-parameters>
        <value>2</value>
        <hardness>10</hardness>
        <rarity>very rare</rarity>
    </precious>
    <semiprecious name="amethyst">
        <preciousness>semiprecious</preciousness>
        <origin>Brazil</origin>
        <visual-parameters>
            <color>violet</color>
            <transparency>70</transparency>
            <lustre>vitreous</lustre>
        </visual-parameters>
        <value>5.2</value>
        <hardness>7</hardness>
        <price>300</price>
    </semiprecious>
    <semiprecious name="garnet">
        <preciousness>semiprecious</preciousness>
        <origin>Russia</origin>
        <visual-parameters>
            <color>red</color>
            <transparency>75</transparency>
            <lustre>vitreous</lustre>
        </visual-parameters>
        <value>4.2</value>
        <hardness>8</hardness>
        <price>600</price>
    </semiprecious>
    <semiprecious name="malachite">
        <preciousness>semiprecious</preciousness>
        <origin>Kazakhstan</origin>
        <visual-parameters>
            <color>green</color>
            <transparency>0</transparency>
            <lustre>silky</lustre>
        </visual-parameters>
        <value>3.9</value>
        <hardness>3</hardness>
        <price>250</price>
    </semiprecious>
</gems>
